name: Run CI tests

on:
  - push
  - pull_request

jobs:
  build:
    name: eclingo ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: install prerequisites
      shell: pwsh
      run: pip install -r requirements.txt

    - name: install dev prerequisites
      shell: pwsh
      run: pip install -r .github/requirements.txt

    - name: python info
      shell: pwsh
      run: python -VV

    - name: clingo info
      shell: pwsh
      run: clingo --version

    - name: install eclingo
      shell: pwsh
      run: python -m pip install .

    - name: test
      shell: pwsh
      run: coverage run -m unittest discover -v

    # - name: type check
    #   shell: pwsh
    #   run: mypy -p clingox

    # - name: lint (pylint)
    #   if: ${{ matrix.python-version != '3.6' }}
    #   shell: pwsh
    #   run: pylint clingox

    # - name: lint (flake8)
    #   shell: pwsh
    #   run: flake8

    # - name: coverage
    #   shell: pwsh
    #   run: coverage report --fail-under=100
